cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'
urlpatterns = [
    path('', cart_detail_view, name="cart_detail"),
    path('add_cart/<int:product_id>/', add_to_cart_view, name="cart_add"),
    path('remove_cart/<int:product_id>/', remove_from_cart, name="cart_remove"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('pages.urls')),
                  path('accounts/', include('allauth.urls')),
                  path('products/', include('products.urls')),
                  path('rosetta/', include('rosetta.urls')),
                  path('cart/', include('cart.urls')),
                  path('i18n/', include('django.conf.urls.i18n')),
                  path('orders/', include('orders.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import *
app_name = 'order'
urlpatterns = [
    path('', order_view, name='order_view')
]

cart/forms.py
from django import forms


class AddToCartProductForm(forms.Form):
    QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 31)]
    # coerce for output form include int this form
    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)
    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from products.models import Product
from .cart import Cart
from .forms import AddToCartProductForm


# Create your views here.


def cart_detail_view(request):
    cart = Cart(request)
    for item in cart:
        item['product_update_quantity_form'] = AddToCartProductForm(initial={
            'quantity': item['quantity'],
            'inplace': True
        })
    return render(request,
                  "cart/cart_detail.html",
                  {
                      'cart': cart,
                  })


@require_POST
def add_to_cart_view(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = AddToCartProductForm(request.POST)
    if form.is_valid():
        clean_data = form.cleaned_data
        quantity = clean_data['quantity']
        cart.add(product, quantity, replace_current_quantity=clean_data['inplace'])

    return redirect('cart:cart_detail')


def remove_from_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

cart/templates/cart/cart_detail.html
{% extends "_base.html" %}

{% load i18n %}
{% load persian_translation_tag %}
{% load humanize %}
{% block title_page %}
    Cart_Detail
{% endblock title_page %}


{% block content_page %}

    <div class="main-content-wrapper">
        <div class="page-content-inner ptb--80">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mb-md--50">

                        <div class="row no-gutters">
                            <div class="col-12">
                                <div class="table-content table-responsive">
                                    {% if cart %}
                                        <table class="table text-center">
                                        <thead>
                                        <tr>
                                            <th>&nbsp;</th>
                                            <th>عکس محصول</th>
                                            <th>نام محصول</th>
                                            <th>قیمت</th>
                                            <th>مقدار</th>
                                            <th>مجموع</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for item in cart %}
                                            <tr>
                                                <td class="product-remove p-0 m-0">
                                                    <a href="{% url 'cart:cart_remove' item.product_obj.id %}"><i
                                                            class="flaticon flaticon-cross"></i>
                                                    </a>
                                                </td>
                                                <td class="product-thumbnail small text-right p-0">
                                                    <img src="{{ item.product_obj.image.url }}">
                                                    >
                                                </td>
                                                <td class="product-name wide-column">
                                                    <h3>
                                                        <a href="{% url 'product_detail' item.product_obj.id %}">{{ item.product_obj.title }}</a>
                                                    </h3>
                                                </td>
                                                <td class="product-price">
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{{ item.product_obj.price|intcomma:False|translate_number  }}</span>
                                                            </span>
                                                </td>
                                                <td class="product-quantity">
                                                    <form class="d-flex"
                                                          action="{% url 'cart:cart_add' item.product_obj.id %}"
                                                          method="post">
                                                        {% csrf_token %}
                                                        <div class="quantity">
                                                            <input type="number" class="quantity-input" name="quantity"
                                                                   id="qty-1" value="{{ item.quantity  }}" min="1">
                                                            {{ item.product_update_quantity_form.inplace }}
                                                        </div>
                                                        <button class="small" type="submit"><i class="fa fa-refresh"></i></button>
                                                    </form>
                                                </td>
                                                <td class="product-total-price">
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{{ item.total_price|intcomma:False|translate_number  }}</span>
                                                            </span>
                                                </td>
                                            </tr>
                                        {% endfor %}


                                        </tbody>
                                    </table>
                                        {% else %}
                                        <p>{% trans 'The cart is Empty.Please Add To cart!' %}</p>
                                        <a href="{% url 'product_list' %}">{% trans 'Go Shopping!' %}</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="row no-gutters border-top pt--20 mt--20">
                            <div class="col-sm-6 text-sm-right">

                            </div>
                        </div>

                    </div>
                    <div class="col-lg-4">
                        <div class="cart-collaterals">
                            <div class="cart-totals">
                                <h5 class="font-size-14 font-bold mb--15">مجموع</h5>
                                <div class="cart-calculator">

                                    <div class="cart-calculator__item order-total">
                                        <div class="cart-calculator__item--head">
                                            <span>جمع کل</span>
                                        </div>
                                        <div class="cart-calculator__item--value">
                                                <span class="product-price-wrapper">
                                                    <span class="money">{{cart.get_total_price|intcomma:False|translate_number }} {% translate 'dollar'%}</span>
                                                </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url 'order:order_view' %}" class="btn btn-fullwidth btn-bg-red btn-color-white btn-hover-2">
                                ثبت سفارش
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock content_page %}