cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'
urlpatterns = [
    path('', cart_detail_view, name="cart_detail"),
    path('add_cart/<int:product_id>/', add_to_cart_view, name="cart_add"),
    path('remove_cart/<int:product_id>/', remove_from_cart, name="cart_remove"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('pages.urls')),
                  path('accounts/', include('allauth.urls')),
                  path('products/', include('products.urls')),
                  path('rosetta/', include('rosetta.urls')),
                  path('cart/', include('cart.urls')),
                  path('i18n/', include('django.conf.urls.i18n')),
                  path('orders/', include('orders.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import *
app_name = 'order'
urlpatterns = [
    path('', order_view, name='order_view')
]

templates/_base.html
{% load static %}
{% load i18n %}
{% load persian_translation_tag %}
{% load humanize %}
<!doctype html>
<html lang="fa" class="no-js">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title_page %}{% endblock title_page %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'img/icon.png' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- ************************* CSS Files ************************* -->

    <link rel="stylesheet" href="{% static 'css/_base.css' %}">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="{% static 'css/vendor.css' %}">

    <!-- style css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">


</head>

<body dir='rtl'>
<div class="wrapper">
    <!-- Header Start -->
    <header class="header">
        <div class="header-inner fixed-header">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-9 col-lg-8 col-5 col-xs-0 col-none col-sm-block p-0">
                        <nav class="main-navigation">
                            <div class="site-branding" style="margin-right: 30px;">
                                <a href="{% url 'home' %}" class="logo">
                                    <figure class="logo--normal d-none d-sm-block">
                                        <img class="px-5" src="{% static 'img/shop_logo.png' %}"
                                             style="max-height: 50px; margin-bottom: -15px;" alt="Logo">
                                    </figure>
                                </a>
                            </div>
                            <div class="mainmenu-nav d-none d-lg-block w-100 pr-3">
                                <ul class="mainmenu d-lg-flex jusity-content-end jusity-content-lg-start pt-4">
                                    <li class="mainmenu__item menu-item-has-children active">
                                        <a href="{% url 'product_list' %}" class="mainmenu__link">
                                            <span class="mm-text">{% trans 'home' %}</span>
                                        </a>
                                    </li>
                                    <li class="mainmenu__item menu-item-has-children">
                                        <a href="Blog.html" class="mainmenu__link">
                                            <span class="mm-text">وبلاگ</span>
                                        </a>
                                    </li>
                                    <li class="mainmenu__item menu-item-has-children">
                                        <a href="#" class="mainmenu__link">
                                            <span class="mm-text">{% translate 'pages' %}</span>
                                        </a>
                                    </li>
                                    <li class="mainmenu__item">
                                        <a href="{% url 'about_us' %}" class="mainmenu__link">
                                            <span class="mm-text">{% translate 'about us' %}</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                    <div class="col-xl-3 col-lg-4 col-sm-7 col-12 p-0">
                        <ul class="header-toolbar">
                            <li class="header-toolbar__item">
                                <a href="wishlist.html" class="header-toolbar__btn mx-4">
                                    <i class="flaticon flaticon-like"></i>
                                </a>
                            </li>
                            <li class="header-toolbar__item mini-cart-item">
                                <a href="#miniCart" class="header-toolbar__btn toolbar-btn mini-cart-btn">
                                    <i class="flaticon flaticon-shopping-cart"></i>
                                    <sup class="mini-cart-count">{{ cart|length|translate_number }}</sup>
                                </a>
                            </li>
                            <li class="header-toolbar__item user-info">
                                <a href="my-account.html" class="header-toolbar__btn">
                                    <i class="flaticon flaticon-user"></i>
                                </a>
                                <ul class="user-info-menu">
                                    {% if user.is_authenticated %}
                                        <li>
                                            <a class="text-right"
                                               href="{% url 'account_logout' %}">{% translate 'Log Out' %}</a>
                                        </li>
                                        <li>
                                            <a class="text-right"
                                               href="{% url 'cart:cart_detail' %}">{% translate 'Card List' %}</a>
                                        </li>
                                    {% else %}
                                        <li>
                                            <a class="text-right"
                                               href="{% url 'account_login' %}">{% translate 'Log In' %}</a>
                                        </li>
                                        <li>
                                            <a class="text-right"
                                               href="{% url 'account_signup' %}">{% translate 'Sign in' %}</a>
                                        </li>
                                    {% endif %}


                                </ul>
                            </li>
                            <li class="header-toolbar__item">
                                <a href="#searchForm" class="header-toolbar__btn toolbar-btn">
                                    <i class="flaticon flaticon-search"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="mobile-menu"></div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header End -->

    {% if messages %}
        <div class="container">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>

    {% endif %}
    {% block content_page %}

    {% endblock content_page %}

    <!-- Footer Start-->
    <footer class="footer">
        <div class="footer-top bg-color ptb--50" data-bg-color="#f6f6f6">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-9 text-center">
                        <div class="footer-widget mb--50">

                        </div>
                        <div class="footer-widget mb--50 pb--1">
                            <ul class="footer-menu">
                                <li><a href="">درباره ما</a></li>
                                <li><a href="">قوانین و مقررات</a></li>
                                <li><a href="{% url 'about_us' %}">تماس با ما</a></li>
                            </ul>
                        </div>
                        <div class="footer-widget">
                            © | all rights reserved
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer End-->

    <!-- Search form Popup Start -->
    <div class="searchform__popup" id="searchForm">
        <a href="#" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
        <div class="searchform__body">
            <p>در باکس زیر عبارت خود را وارد کنید</p>
            <form class="searchform">
                <input type="text" name="popup-search" id="popup-search" class="searchform__input"
                       placeholder="جستجو در بین محصولات...">
                <button type="submit" class="searchform__submit"><i class="flaticon flaticon-magnifying-glass-icon"></i>
                </button>
            </form>
        </div>
    </div>
    <!-- Search form Popup End -->

    <!-- Mini Cart Start -->
    <aside class="mini-cart" id="miniCart">
        <div class="mini-cart-wrapper">
            <a href="" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
            <div class="mini-cart-inner">
                <h3 class="mini-cart__heading mb--40 mb-lg--30 text-right">{% translate 'Cart' %}</h3>
                <div class="mini-cart__content">
                    <ul class="mini-cart__list text-right">
                        {% for item in cart %}
                            <li class="mini-cart__product d-flex justify-content-between">
                                <div class="mini-cart__product__image">
                                    <a href="#">
                                        <img src="assets/img/products/prod-1-100x100.jpg">
                                    </a>
                                </div>
                                <div class="mini-cart__product__content pt-2">
                                <span class="mini-cart__product__title d-flex flex-row justify-content-between">
                                    <a href="#">{{ item.product_obj.title }}</a>
                                    <a href="#" class="">
                                        &#10060;
                                    </a>
                                </span>
                                    <span class="mini-cart__product__quantity">
                                    <span>{{ item.product_obj.price }}</span> &#215; <span>{{ item.quantity }}</span>
                                </span>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                    <div class="mini-cart__total">
                        <span>{% translate 'Total' %}</span>
                        <span class="ammount">{{ cart.get_total_price }} {% translate '$' %}</span>
                    </div>
                    <div class="mini-cart__buttons">
                        <a href="{% url 'cart:cart_detail' %}"
                           class="btn btn-fullwidth btn-bg-sand mb--20">{% translate 'Go to cart' %}</a>
                        {% if not cart.is_empty %}
                            <a href="{% url 'order:order_view' %}"
                               class="btn btn-fullwidth btn-bg-sand">{% translate 'Checkout' %}</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </aside>
    <!-- Mini Cart End -->

    <!-- jQuery JS -->
    <script src="{% static '/js/vendor.js' %}"></script>

    <!-- Main JS -->
    <script src="{% static '/js/main.js' %}"></script>
</div>

</body>

</html>

templates/about_us.html
{% extends '_base.html' %}
{% load i18n %}

{% block title_page %}
    {% translate 'About Us' %}
{% endblock %}

{% block content_page %}
    <!-- Breadcrumb area Start -->
    <div class="breadcrumb-area bg-color ptb--90" data-bg-color="#f6f6f6">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="d-flex justify-content-between align-items-center flex-sm-row flex-column">
                        <h1 class="page-title">تماس با ما</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb area End -->

    <!-- Main Content Wrapper Start -->
    <div id="content" class="main-content-wrapper">
        <div class="page-content-inner pt--75">
            <div class="container">
                <div class="row pb--80">
                    <div class="col-md-7 mb-sm--30">
                        <h2 class="heading__secondary mb--50 mb-md--35 mb-sm--20">پیام خود را به ما بگویید</h2>

                        <!-- Contact form Start Here -->
                        <form class="form" action="mail.php" id="contact-form">
                            <div class="form__group mb--20">
                                <input type="text" id="contact_name" name="contact_name"
                                       class="form__input form__input--2" placeholder="نام*">
                            </div>
                            <div class="form__group mb--20">
                                <input type="email" id="contact_email" name="contact_email"
                                       class="form__input form__input--2" placeholder="ایمیل*">
                            </div>
                            <div class="form__group mb--20">
                                <input type="text" id="contact_phone" name="contact_phone"
                                       class="form__input form__input--2" placeholder="شماره تماس*">
                            </div>
                            <div class="form__group mb--20">
                                <textarea class="form__input form__input--textarea" id="contact_message"
                                          name="contact_message" placeholder="پیام شما*"></textarea>
                            </div>
                            <div class="form__group">
                                <button type="submut" class="btn-submit">ارسال</button>
                            </div>
                            <div class="form__output"></div>
                        </form>
                        <!-- Contact form end Here -->

                    </div>
                    <div class="col-md-5 pl--50 pl-sm--30">
                        <h2 class="heading__secondary mb--50">اطلاعات تماس</h2>

                        <!-- Contact info widget start here -->
                        <div class="contact-info-widget mb--45">
                            <div class="contact-info">
                                <h3 class="heading__tertiary">آدرس پستی</h3>
                                <p>مکانی در خیابان کوچه فلان <br> ایران تهران </p>
                            </div>
                        </div>
                        <!-- Contact info widget end here -->

                        <!-- Contact info widget start here -->
                        <div class="contact-info-widget mb--45">
                            <div class="contact-info">
                                <h3 class="heading__tertiary">شاپینگ یار</h3>
                                <p>مکانی در خیابان کوچه فلان <br> ایران تهران </p>
                            </div>
                        </div>
                        <!-- Contact info widget end here -->

                        <!-- Contact info widget start here -->
                        <div class="contact-info-widget two-column-list sm-one-column mb--45">
                            <div class="contact-info mb-sm--35">
                                <h3 class="heading__tertiary">شماره تماس</h3>
                                <a href="">+98912345678</a>
                            </div>
                            <div class="contact-info">
                                <h3 class="heading__tertiary">ایمیل</h3>
                                <a href="mailto:info@la-studioweb.com">info@codingyar.com</a>
                            </div>
                        </div>
                        <!-- Contact info widget end here -->

                        <!-- Social Icons Start Here -->
                        <ul class="social social-sharing">
                            <li class="social__item">
                                <a href="https://instagram.com/m.hadi.hajihosseini" class="social__link instagram">
                                    <i class="fa fa-instagram"></i>
                                </a>
                            </li>
                        </ul>
                        <!-- Social Icons End Here -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Main Content Wrapper Start -->

{% endblock %}

templates/home.html
{% extends "_base.html" %}

{% block title_page %} Home {% endblock title_page %}

{% block content_page %}

<h1>Home Page</h1>

{% endblock content_page %}